sudo: required
services:
  - docker

language: java
jdk: oraclejdk8

branches:
  only:
    - master

before_install:
  - docker version
  - docker info
  - node --version
  - npm --version

script:
  - cd src/main/resources
  - pwd
  - npm install -g gulp
  - npm install
  - gulp minify
  - cd ../../../
  - mvn clean verify -f pom.xml -e

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker images
  - docker push tokyomotel/alma-server:latest
  
deploy:
  provider: releases
  api_key: $API_KEY_GIT
  file: README.md
  skip_cleanup: true
  on:
    tags: true

