sudo: required

language: java
jdk: oraclejdk8

branches:
  only:
    - master
    - HEROKU

script:
  - cd src/main/resources
  - pwd
  - npm install -g gulp
  - npm install
  - gulp minify
  - cd ../../../
  - mvn clean verify -f pom.xml -e
  
deploy:
  provider: releases
  api_key: $API_KEY_GIT
  file: README.md
  skip_cleanup: true
  on:
    tags: true

